/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [],
  timeFormat: 12,
  units: 'imperial',
  modules: [
    {
      module: 'MMM-Remote-Control',
      config: {
        secureEndpoints: false
      }
    },
    {
      module: 'MMM-Sounds',
      config: {
        startupSound: 'wobble.wav',
        quietTimeStart: '21:00',
        quietTimeEnd: '07:00'
      }
    },
    {
      module: 'MMM-ModuleScheduler',
      config: {
        notification_schedule: [
          {
            notification: 'REMOTE_ACTION',
            schedule: '00 6 * * *',
            payload: {
              action: 'MONITORON'
            }
          },
          {
            notification: 'REMOTE_ACTION',
            schedule: '30 22 * * *',
            payload: {
              action: 'MONITOROFF'
            }
          }
        ]
      }
    },
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'clock',
      position: 'top_center',
      config: {}
    },
    {
      disabled: false,
      module: 'MMM-Carousel',
      position: 'bottom_bar',
      config: {
        transitionInterval: 0,
        ignoreModules: [
          'clock',
          'alert',
          'MMM-Wallpaper',
          'MMM-MQTTbridge',
          'MMM-RemoteControl',
          'MMM-StopwatchTimer'
        ],
        mode: 'slides',
        slides: {
          home: [
            'MMM-CalendarExt2',
            'currentweather',
            'weatherforecast',
            'MMM-Todoist',
            'MMM-homeassistant-sensors',
            'calendar'
          ],
          video: [
            'MMM-RTSPStream'
          ],
          timer: [
            'MMM-OClock'
          ]
        },
        keyBindings: {
          enabled: true,
          mode: 'DEFAULT',
          map: {
            NextSlide: 'ArrowRight',
            PrevSlide: 'ArrowLeft',
            Slide0: 'Home'
          }
        }
      }
    },
    {
      module: 'MMM-MQTTbridge',
      disabled: true,
      config: {
        mqttServer: 'mqtt://${mqttusername}:${mqttpassword}@${mqttserverip}:1883',
        mqttConfig: {
          listenMqtt: true,
          interval: 120000
        },
        notiConfig: {
          listenNoti: true,
          ignoreNotiId: [
            'CLOCK_MINUTE',
            'NEWS_FEED'
          ],
          ignoreNotiSender: [
            'system',
            'NEWS_FEED'
          ]
        }
      },
      header: '',
      position: ''
    },
    {
      module: 'MMM-OClock',
      position: 'top_center',
      config: {
        centerColor: '#00000',
        centerR: 250,
        centerTextFormat: 'm:ss',
        centerFont: 'bold 120px Roboto',
        centerTextColor: '#FFFFFF',
        hands: [
          'minute',
          'second'
        ],
        handWidth: [
          40,
          40,
          40,
          40,
          60,
          50
        ],
        colorType: 'static',
        colorTypeStatic: [
          'green',
          'black',
          'yellow',
          'green',
          'blue',
          'green'
        ],
        handConversionMap: {
          year: 'YYYY',
          month: 'M',
          date: 'D',
          week: 'w',
          day: 'e',
          hour: 'h',
          minute: 'm',
          second: 's'
        },
        secondsUpdateInterval: 2,
        canvasStyle: 'opacity: .3;'
      }
    },
    {
      module: 'MMM-RTSPStream',
      disabled: false,
      position: 'middle_center',
      config: {
        rotateStreams: true,
        moduleWidth: 1280,
        moduleHeight: 960,
        localPlayer: 'omxplayer',
        showSnapWhenPaused: false,
        remoteSnaps: false,
        shutdownDelay: 12,
        stream1: {
          name: 'Driveway',
          url: 'rtmp://192.168.0.130/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=${videopassword}',
          frameRate: '15',
          protocol: 'udp',
          width: 1024,
          height: 768
        }
      }
    },
    {
      module: 'MMM-StopwatchTimer',
      config: {}
    },
    {
      disabled: false,
      module: 'currentweather',
      position: 'top_right',
      config: {
        location: 'St.Louis',
        locationID: '4407066',
        appid: '${weatherappid}',
        colored: 'true',
        roundTemp: true
      }
    },
    {
      disabled: false,
      module: 'weatherforecast',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        fade: false,
        fadePoint: 1,
        showRainAmount: true,
        tableClass: 'medium',
        location: 'St. Louis',
        roundTemp: true,
        locationID: '4407066',
        appid: '${weatherappid}'
      }
    },
    {
      disabled: false,
      module: 'MMM-CalendarExt2',
      config: {
        updateInterval: 600000,
        calendars: [
          {
            name: 'Family',
            url: '${icspath}',
            scanInterval: 300000
          }
        ],
        views: [
          {
            name: 'My Calendar',
            mode: 'week',
            slotCount: 3,
            slotMaxHeight: '100px',
            position: 'bottom_bar',
            timeFormat: 'h:mm A',
            calendars: [
              'Family'
            ]
          }
        ],
        scenes: [
          {
            name: 'DEFAULT'
          }
        ]
      }
    },
    {
      module: 'MMM-KeyBindings',
      config: {
        evdev: {
          enabled: false
        },
        enableKeyboard: true
      }
    },
    {
      module: 'MMM-homeassistant-sensors',
      position: 'top_left',
      config: {
        host: '192.168.0.124',
        port: '8123',
        https: false,
        token: '${hatoken}',
        prettyName: false,
        stripName: false,
        debuglogging: false,
        values: [
          {
            sensor: 'sensor.processor_use_percent',
            alertThreshold: 50,
            icons: [
              {
                default: 'chip'
              }
            ]
          },
          {
            sensor: 'sensor.driveway_person',
            icons: [
              {
                state_off: 'run',
                state_on: 'run-fast'
              }
            ],
            attributes: [
              'last_updated',
              'state.last_updated'
            ]
          },
          {
            sensor: 'automation.driveway_car_notification',
            icons: [
              {
                state_off: 'run',
                state_on: 'run-fast'
              }
            ],
            attributes: [
              'last_triggered',
              'state'
            ]
          }
        ]
      }
    },
    {
      module: 'MMM-TTS',
      position: 'top_right',
      config: {}
    },
    {
      disabled: false,
      module: 'MMM-Wallpaper',
      position: 'fullscreen_below',
      config: {
        source: 'firetv',
        slideInterval: 180000,
        maximumEntries: 30
      }
    },
    {
      module: 'MMM-Todoist',
      position: 'top_left',
      header: 'Alexa Shopping',
      tableclass: 'medium',
      config: {
        accessToken: '${todoisttoken}',
        maximumEntries: 60,
        updateInterval: 300000,
        projects: [
          2193000698
        ],
        fade: false,
        showProject: false,
        orderBy: 'dueDateAsc'
      }
    },
    {
      module: 'MMM-Todoist',
      position: 'top_left',
      header: 'To Dos',
      config: {
        accessToken: '${todoisttoken}',
        maximumEntries: 60,
        updateInterval: 300000,
        projects: [
          2230070598
        ],
        fade: false,
        showProject: false
      }
    },
    {
      disabled: false,
      module: 'calendar',
      header: 'Family Calendar',
      position: 'top_center',
      config: {
        maximumEntries: 8,
        maxTitleLength: 50,
        wrapEvents: true,
        fade: false,
        dateFormat: 'ddd M/D h:mm',
        fullDayEventDateFormat: 'ddd M/D',
        tableClass: 'medium',
        timeFormat: 'absolute',
        getRelative: 0,
        urgency: 0,
        fetchInterval: 420000,
        calendars: [
          {
            symbol: 'calendar',
            url: '${icspath}'
          }
        ]
      }
    }
  ]
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
